# Generated by Django 3.2 on 2022-06-09 11:38

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletterrecepients',
            name='name',
            field=models.CharField(blank=True, default=django.contrib.auth.models.User, max_length=30),
        ),
    ]
