# Generated by Django 3.2 on 2022-06-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsletterrecepients_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletterrecepients',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
